# Railway Configuration for SaasLiteLLM Project
# This file configures both LiteLLM Proxy and SaaS API services

# Default configuration (will be used by services that don't have specific config)
[build]
builder = "dockerfile"

[deploy]
healthcheckTimeout = 100
restartPolicyType = "on_failure"

# Service-specific configurations
# Railway will match these by service name

# LiteLLM Proxy Service
[environments.production.services.SaasLiteLLM]
build.dockerfilePath = "Dockerfile"
deploy.startCommand = "--config /app/config.yaml --port 4000 --detailed_debug"
deploy.healthcheckPath = "/health"

# SaaS API Service
[environments.production.services.saas-api]
build.dockerfilePath = "Dockerfile.saas"
deploy.healthcheckPath = "/health"
