# Railway Configuration for SaasLiteLLM Project
# Each service uses Root Directory setting in Railway dashboard:
# - LiteLLM Proxy: Root Directory = services/litellm
# - SaaS API: Root Directory = services/saas-api

[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
