# Models are managed via database - add them through the dashboard UI
# Visit http://localhost:8002/ui to add models
model_list: []

# General settings
general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL
  store_model_in_db: true  # Enable model management via dashboard

  # Redis caching for faster responses and cost savings
  cache: true
  cache_params:
    type: "redis"
    host: os.environ/REDIS_HOST
    port: os.environ/REDIS_PORT
    password: os.environ/REDIS_PASSWORD
    ttl: 600  # Cache responses for 10 minutes

  # Cost tracking per team
  track_cost_per_deployment: true

# Router settings
router_settings:
  redis_host: os.environ/REDIS_HOST
  redis_port: os.environ/REDIS_PORT
  redis_password: os.environ/REDIS_PASSWORD
  enable_pre_call_checks: true

  # Rate limiting using Redis
  routing_strategy: "usage-based-routing"  # Smart routing based on usage
  num_retries: 3
  timeout: 600

  # Redis-based rate limiting per team
  redis_enabled: true
  
# Teams configuration with rate limiting and budgets
teams:
  - team_id: team_1
    team_alias: "development-team"
    members_with_roles:
      - role: "admin"
        user_id: "dev-admin"
    metadata:
      department: "engineering"
      budget_limit: 1000
    models:
      - "gpt-3.5-turbo"
      - "claude-3-sonnet"
    max_budget: 1000.0  # Monthly budget in USD
    budget_duration: "30d"  # Reset every 30 days
    tpm_limit: 10000  # Tokens per minute limit
    rpm_limit: 100  # Requests per minute limit

  - team_id: team_2
    team_alias: "production-team"
    members_with_roles:
      - role: "admin"
        user_id: "prod-admin"
    metadata:
      department: "production"
      budget_limit: 5000
    models:
      - "gpt-4-turbo"
      - "claude-3-opus"
      - "claude-3-sonnet"
    max_budget: 5000.0  # Monthly budget in USD
    budget_duration: "30d"
    tpm_limit: 50000  # Higher limits for production
    rpm_limit: 500
