# Models are managed via database - add them through the dashboard UI
# Visit http://localhost:8002/ui to add models
model_list: []

# General settings
general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL
  store_model_in_db: true  # Enable model management via dashboard
  
# Router settings (Redis for caching only)
router_settings:
  redis_host: os.environ/REDIS_HOST
  redis_port: os.environ/REDIS_PORT
  redis_password: os.environ/REDIS_PASSWORD
  enable_pre_call_checks: true